#!/usr/local/bin/node

var argv = require('optimist').argv;
var colors = require('colors');
var request = require('request');
var query = argv.query;
var color = argv.color;
if(!query){
console.log("minimally pass in --query \"your query\", --color toggles highlighting");
process.exit(0);
}
search(query, color);

function search(query, color) {
    var base = 'https://query.yahooapis.com/v1/public/yql?q=';
    var enc = encodeURIComponent(query);
    var end = '&format=json&diagnostics=true&callback=';
    var req = base + enc + end;
    request(req, function (error, response, body) {
        if (!error && response.statusCode == 200) {
            var jsonobj = JSON.parse(body);
            //do some parsing here ?
            var resp = JSON.stringify(jsonobj, null, 4);
            if (color) {
                console.log(colorize(resp));
            } else {
                console.log(resp);
            }
        } else {
            console.log('something went wrong');
        }
    })
}

//http://stackoverflow.com/questions/4810841/how-can-i-pretty-print-json-using-javascript
function colorize(json) {
  
    colors.setTheme({
        null: 'grey',
        number: 'cyan',
        key: 'red',
        string: 'green',
        boolean: 'blue',
    });
  
    return json.replace(/("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)/g, function (match) {
        var cls = 'number';
        if (/^"/.test(match)) {
            if (/:$/.test(match)) {
                cls = 'key';
            } else {
                cls = 'string';
            }
        } else if (/true|false/.test(match)) {
            cls = 'boolean';
        } else if (/null/.test(match)) {
            cls = 'null';
        }
        return match[cls];
    });
}
